name: 打包VUE项目

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 读取仓库内容策略2
        run: |
          npm install

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: build



