name: 打包VUE项目

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - run: |
        name: 读取仓库内容策略1
      - uses: actions/checkout@v4

      - name: 读取仓库内容策略2
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 部署
        run: |
          npm install
          npx webpack
